### ISSUE TITLE
General Query

### ISSUE THREAD

**Issue by neilmartis** [opendata/How-To#25]
Hi All

I have a general query.The city that I live in uses data from ARCGIS does it count as open data and does it need to have a license under creative commons http://opendata.city-of-waterloo.opendata.arcgis.com/  http://www.waterloo.ca/en/government/GetTheData.asp
Thanks,
Neil

**Comment by waldoj** [comment]
[These are the 8 principles of open government data](https://opengovdata.org/). Data is not either open or closed—it exists somewhere on a spectrum of openness.
